name: Test RangeMessage.xml is well-formed.
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout isbn-rs
      uses: actions/checkout@v2
      with:
        repository: "philippeitis/isbn-rs"
    - name: cd
      run: cd ..
    - name: checkout range messages
      uses: actions/checkout@v2
    - name: cd
      run: cd ..
    - name: remove old range messages
      run: ls && rm -r isbn-rs/range-messages
    - name: copy new range messages
      run: mv range-messages isbn-rs/range-messages
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    - name: test  
      run: cd isbn-rs && cargo test
